export enum DatabaseType {
    MYSQL = 'mysql',
    ORACLE = 'oracle',
    MSSQL = 'mssql',
    MONGODB = 'mongodb',
    POSTGRES = 'postgres',
    COCKROACHDB = 'cockroachdb',
    SAP = 'sap',
    MARIADB = 'mariadb',
    SQLITE = 'sqlite',
    CORDOVA = 'cordova',
    REACT_NATIVE = 'react-native',
    NATIVESCRIPT = 'nativescript',
    SQLJS = 'sqljs',
    AURORA_MYSQL = 'aurora-mysql',
    AURORA_POSTGRES = 'aurora-postgres',
    EXPO = 'expo',
    BETTER_SQLITE3 = 'better-sqlite3',
    CAPACITOR = 'capacitor',
    SPANNER = 'spanner'
}